# Generated by Django 2.2.5 on 2019-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0002_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(default='sample summary', max_length=255, unique=True),
        ),
    ]
