# Generated by Django 2.2.5 on 2019-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0003_auto_20191126_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
