# Generated by Django 2.2.5 on 2019-11-27 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dlblog', '0004_auto_20191126_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_main_image',
            field=models.FileField(upload_to='static/images/'),
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usecase_main_image', models.FileField(upload_to='static/images/')),
                ('usecase_title', models.CharField(max_length=255, unique=True)),
                ('usecase_summary', models.CharField(max_length=255, unique=True)),
                ('usecase_slug', models.SlugField(max_length=200, unique=True)),
                ('usecase_updated_on', models.DateTimeField(auto_now=True)),
                ('usecase_content', models.TextField()),
                ('usecase_created_on', models.DateTimeField(auto_now_add=True)),
                ('usecase_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('usecase_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecase_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usecase_created_on'],
            },
        ),
    ]
