# Generated by Django 2.2.5 on 2019-11-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0006_auto_20191128_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_main_image',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
