# Generated by Django 2.2.5 on 2019-11-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0007_auto_20191128_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_main_image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_main_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
