# Generated by Django 2.2.5 on 2019-11-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0010_auto_20191128_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_summary',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
