# Generated by Django 2.2.5 on 2019-12-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0016_blog1_blog_main_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog1',
            new_name='MyBlog',
        ),
    ]
