# Generated by Django 2.2.5 on 2019-12-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0017_auto_20191206_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='blog_main_image',
        ),
    ]
