# Generated by Django 2.2.5 on 2019-12-06 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0018_remove_myblog_blog_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
