# Generated by Django 2.2.5 on 2019-12-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0019_myblog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBlog',
        ),
    ]
