# Generated by Django 2.2.5 on 2019-12-10 09:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0020_delete_myblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=80, unique=True),
        ),
    ]
