# Generated by Django 2.2.5 on 2019-12-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0021_auto_20191210_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
