# Generated by Django 2.2.5 on 2019-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0022_auto_20191211_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
