# Generated by Django 2.2.8 on 2019-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0023_auto_20191211_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='usecase_summary',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_title',
            field=models.CharField(max_length=50),
        ),
    ]
