# Generated by Django 2.2.8 on 2019-12-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0024_auto_20191212_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='usecase_summary',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
