# Generated by Django 2.2.8 on 2019-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0026_auto_20191212_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='usecase_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_summary',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
