# Generated by Django 2.2.8 on 2019-12-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0028_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='usecase_slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_summary',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='usecase_title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
