# Generated by Django 2.2.8 on 2019-12-15 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0031_auto_20191215_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_main_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='blog/images/'),
            preserve_default=False,
        ),
    ]
