# Generated by Django 2.2.8 on 2019-12-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlblog', '0035_auto_20191216_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
