# Generated by Django 2.2.5 on 2019-12-19 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_main_image', models.FileField(upload_to='blog/images/')),
                ('course_title', models.CharField(max_length=200, null=True)),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('course_slug', models.SlugField(max_length=200, unique=True)),
                ('course_created_on', models.DateTimeField(auto_now_add=True)),
                ('course_status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('course_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-course_created_on'],
            },
        ),
    ]
